version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - echo Installing npm and installing npm packages $(date)
      - apt-get install -y curl nodejs
      - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
      - export NVM_DIR="$HOME/.nvm"
      - [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
      - [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
      - nvm install stable
      - npm install --production
  build:
    commands:
      - echo Build starting $(date)
      - make package
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - mattermost-webapp-tar.gz
