version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - echo Installing npm and installing npm packages $(date)
      - apt-get install -y curl nodejs
      - curl -L https://www.npmjs.org/install.sh | sh
      - npm install --production
  build:
    commands:
      - echo Build starting $(date)
      - make package
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - mattermost-webapp-tar.gz
