version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - apt update -y
      - apt-get install -y make npm libpng-dev
      - apt-get install -y
  pre_build:
    commands:
      - echo Configuring Build Env $(date)
  build:
    commands:
      - echo Build starting $(date)
      - make package
      - tar -xvf mattermost-webapp.tar.gz
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - client
