version: 0.2

phases:
  pre_build:
    commands:
      - echo Configuring Build Env $(date)
      - aws --version
      - $(aws ecr get-login --region $AWS_REGION --no-include-email)
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-8)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build starting $(date)
      - docker build -f $REPO_URI:latest -t $REPO_URI:latest .
      - docker tag $REPO_URI:latest $REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed $(date)
      - echo Pushing images
      - docker push $REPO_URI:latest
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Writing image definitions file
      - printf '[{"name":"%s","imageUri":"%s"}]' $IMAGE_NAME $REPO_URI:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
