version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - echo Installing npm and installing npm packages $(date)
      - apt-get install -y curl nodejs
      - curl -o- -L https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
      - nvm install stable
      - npm install --production
  build:
    commands:
      - echo Build starting $(date)
      - make package
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - mattermost-webapp-tar.gz
