version: 0.2

phases:
  install:
    commands:
      - echo Installing curl and nodejs
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
      - sudo apt-get install -y nodejs
      - npm cache clean -f
      - npm install -g n
      - n 10.22.0
      - apt update -y
      - nodeversion=$(node -v)
      - npmversion=$(npm version)
      - echo "Node VERSION $nodeversion"
      - echo "NPM VERSON $npmversion"
  build:
    commands:
      - echo Build starting npm install
      - npm cache verify
      - make package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - mattermost-webapp-tar.gz
