version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - echo Installing npm and installing npm packages $(date)
      - apt-get install -y curl make
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash
      - sudo apt-get install -y nodejs
      - rm -rf package-lock.json
      - npm update
      - npm install --production
  build:
    commands:
      - echo Build starting $(date)
      - make package
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - mattermost-webapp-tar.gz
