version: 0.2

phases:
  install:
    commands:
      - apt update -y
      - echo Installing npm and installing npm packages $(date)
      - apt-get install -y curl make
      - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash
      - echo "JS VERSION $(node -v)"
      - echo "NPM VERSION $(npm version)"
  build:
    commands:
      - echo Build starting $(date)
      - make package
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - mattermost-webapp-tar.gz
