version: 0.2

phases:
  install:
    commands:
      - echo Installing curl and nodejs
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
      - apt-get install -y nodejs
      - git clone https://github.com/mattermost/mattermost-redux.git
      - cd mattermost-redux/
      - make bundle
      - cd ..
  build:
    commands:
      - echo Build starting build
      - make package
  post_build:
    commands:
      - echo Build completed, starting upload
      #- scp mattermost-webapp-tar.gz mattermost@EC2-instance:/opt/mattermost
      #- ssh mattermost@ec2-instance
      #- cd/opt/mattermost
      #- rm -r client
      #- tar -xvf --override mattermost-webapp.tar.gz
artifacts:
  files:
    - mattermost-webapp-tar.gz
