version: 0.2

phases:
  install:
    commands:
      - echo Installing curl and nodejs
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
      - sudo apt-get install -y nodejs
      - npm install -g n
      - sudo n 10.22.0
      - npm config set registry http://registry.npmjs.org
      - sudo npm install cwebp-bin cwebp
      - sudo apt update -y
      - git clone https://github.com/mattermost/mattermost-redux.git
      - #nodeversion=$(node -v)
      - #npmversion=$(npm version)
      - #echo "Node VERSION $nodeversion"
      - #echo "NPM VERSON $npmversion"
  build:
    commands:
      - echo Build starting build
      #- npm cache verify
      #- npm install --production
      #- npm install cross-env
      #- npm run build
      - make package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - mattermost-webapp.tar.gz
