version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo CLoneing mattermost redux
      - git clone https://github.com/mattermost/mattermost-redux.git
      - cd mattermost-redux/
      - make bundle
      - cd ..
  build:
    commands:
      - echo Build starting build
      - make package
  post_build:
    commands:
      - echo Build completed, starting upload
      #- echo uploading to staging ec2 instance
      #- scp mattermost-webapp-tar.gz mattermost@EC2-instance:/opt/mattermost
      #- ssh mattermost@ec2-instance
      #- cd/opt/mattermost
      #- rm -r client
      #- tar -xvf mattermost-webapp.tar.gz
artifacts:
  files: mattermost-webapp-tar.gz
