version: 0.2

phases:
  install:
    commands:
      - echo Installing curl and nodejs
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
      - sudo apt-get install -y nodejs
      - npm install -g n
      - sudo n 10.22.0
      - npm config set registry http://registry.npmjs.org
      - sudo npm install cwebp-bin cwebp imagemin-webp
      - sudo apt update -y
      - git clone https://github.com/mattermost/mattermost-redux.git
      - list=$(ls)
      - echo "list $list"
      - cd mattermost-redux/
      - list=$(ls)
      - echo "redux $list"
  build:
    commands:
      - echo Build starting build
      - make package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - mattermost-webapp.tar.gz
