version: 0.2

phases:
  install:
    commands:
      - echo Installing curl and nodejs
      - apt-get install -y curl
      - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash
      - sudo apt-get install -y nodejs
      - git clone https://github.com/mattermost/mattermost-redux.git
      - cd mattermost-redux/
      - make bundle
      - cd ..
  build:
    commands:
      - echo Build starting build
      - make build
  post_build:
    commands:
      - echo Build completed, starting upload
      #- echo uploading to staging ec2 instance
      #- scp -R client mattermost@EC2-instance:/opt/mattermost/client
artifacts:
  files:
    - '**/*'
  base-directory: 'client'
