version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt update -y
      - apt-get install -y
      - echo Installing npm and installing npm packages$(date)
      - apt-get install -y curl
      - curl http://www.npmjs.org/install.sh | sh
      #- npm config set registry="http://registry.npmjs.org/"
      #- npm install npm@latest -g
      - npm install --production
  pre_build:
    commands:
      - echo Configuring Build Env $(date)
  build:
    commands:
      - echo Build starting $(date)
      - make build
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - client
