version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt update -y
      - apt-get install -y
      - echo Installing npm and installing npm packages$(date)
      - apt-get install -y npm
      - npm config set strict-ssl false
      - npm install npm -g
      - npm update -g
      - npm install --production
  build:
    commands:
      - echo Build starting $(date)
      - make package
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - mattermost-webapp-tar.gz
