version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - apt update -y
      - apt-get install -y
      - echo Installing make $(date)
      - apt install -y build-essential
      - echo Installing npm and installing npm packages$(date)
      - apt-get install -y npm
  pre_build:
    commands:
      - echo Configuring Build Env $(date)
  build:
    commands:
      - rm -r package-lock.json
      - echo Build starting $(date)
      - make build
  post_build:
    commands:
      - echo Build completed $(date)
artifacts:
  files:
    - client
